version: '3.7'

services:

    aria2:
        command:
            - 'aria2c'
            - '--dir=/var/lib/seedbox'
            - '--enable-dht=false'
            - '--enable-rpc'
            - '--log=-'
            - '--log-level=notice'
            - '--max-concurrent-downloads=10'
            - '--quiet'
            - '--rpc-listen-all=true'
            - '--rpc-save-upload-metadata=false'
            - '--rpc-secret=${RPC_SECRET}'
        environment:
            - 'USER=nobody'
        image: timonier/aria2:latest
        init: true
        ports:
            - '6800:6800'
        read_only: true
        volumes:
            - 'data:/var/lib/seedbox:rw'

    webui-aria2:
        build:
            context: src/.
            dockerfile: Dockerfile
        environment:
            - 'RPC_HOST=127.0.0.1'
            - 'RPC_PORT=6800'
            - 'RPC_SECRET=${RPC_SECRET}'
        image: timonier/webui-aria2:latest

volumes:

    data: {}
